### ISSUE TITLE
Maybe add a flag to disable executable `large-anon-testsuite-fourmolu-preprocessor`

### ISSUE THREAD

**Issue by johannesgerer** [well-typed/large-records#144]
This executable leads to quite heavy dependencies due to `fourmolu` and nix is not smart enough to ignore this dependency even if the build target is set to the library only.

So having a flag to disable this, would be an easy way to get rid of the dependency in cases where one does not which to run the test.

**Comment by edsko** [comment]
What if we changed the executable type to test suite, and change it's `main` function to just return without errors if there are no arguments passed, so that it could actually run as a test suite too -- then you could just disable the tests. What do you think? Either way, seems reasonable to me, feel free to submit a PR :)

**Comment by edsko** [comment]
Closed in #149 .

**Comment by edsko** [comment]
Thanks for the issue and the PR!
