### ISSUE TITLE
Production usage reports?

### ISSUE THREAD

**Issue by saurabhnanda** [well-typed/large-records#154]
Is `large-anon` being used in production-level projects? Is it recommended/safe to use? Any gotchas (or perf-issues) one needs to be aware of?

**Comment by edsko** [comment]
The library [was developed for Juspay](https://well-typed.com/blog/2022/04/large-anon/), for use in their large codebase (that's why all of [large-anon](https://hackage.haskell.org/package/large-anon), [large-generics](https://hackage.haskell.org/package/large-generics) and [large-records](https://hackage.haskell.org/package/large-records), as well as [typelet](https://hackage.haskell.org/package/typelet) all emphasize compile time performance). Compile time and runtime performance should be good. I'm not currently aware of any safety issues, but of course the library is relatively young so there may well be bugs; if you find any, feel free to open an issue :slightly_smiling_face:  (Or better yet, submit a PR :grimacing: ).
